### ISSUE TITLE
Expense with a minus sign increases the total. 

### ISSUE THREAD

**Issue by angirassahu** [AndreAle94/moneywallet#169] opened 2021-01-12 16:03 UTC
We add expense with minus sign then instead of decreasing the capital it increases it this is problematic as sometimes the whole total is messed up there is also other issue most of the time the total is measured up because the wallet balance in the slide menu is not updated sometimes please look into it

**Comment by AndreAle94** [comment] 2021-01-12 19:29
Duplicate of #93

**Closed by AndreAle94** 2021-01-12 19:29 UTC

**Comment by angirassahu** [comment] 2021-01-12 19:39
This is an amazing app it helps me a lot.
