### ISSUE TITLE
Second decimal digit bug

### ISSUE THREAD

**Issue by essetielle** [AndreAle94/moneywallet#45] opened 2019-01-17 15:28 UTC
When I write 32,98 the app write 32,97

**Comment by AndreAle94** [comment] 2019-01-17 16:39
Duplicate of #32. The issue has been already solved, the fix will be integrated in the next release.

**Closed by AndreAle94** 2019-01-17 16:39 UTC
Labels: duplicate

**Comment by myrdd** [comment] 2021-08-04 09:52
I'm using the latest version (which is v4.0.5.9) from F-Droid, and there's still at least the following bug regarding the second decimal place: The screenshots (german locale) show the following:

* the correct value, seen when editing the transfer is 19.49 EUR
* in the list of transfers, the value is correct
* in the list of **transactions** the value is **1 cent less** (19.48 EUR).

![editing the Trannsfer](https://user-images.githubusercontent.com/4286829/128160083-5a173f6d-8418-46c3-a62a-bcff651423c8.png)
![list of transfers](https://user-images.githubusercontent.com/4286829/128160153-a918d86c-6ad9-4afc-a196-2c9b686bfca4.png)
![list of transactions](https://user-images.githubusercontent.com/4286829/128160179-4e7b11bb-44bb-44df-9343-8c4233fbd1f2.png)

---

PS: Thanks for this really great app!!

**Comment by allan-null** [comment] 2021-09-16 13:41
I can confirm the issue is still present on the latest F-Droid release using the BRL currency.
For now, I've been adding 1 penny transactions in a category called "WORKAROUND" every time this issue happens (it's not often). Just so if anybody wants a way to keep the totals matching too.
