### ISSUE TITLE
net income not displayed correctly

### ISSUE THREAD

**Issue by heptocat** [AndreAle94/moneywallet#42] opened 2019-01-13 09:30 UTC
Version 4.0.4.1 of the app:
In the overview  of all wallets, the net income is displayed by adding the expenses to the income instead of subtracting them. I did enter expenses as negative values. The transactions are shown in separate diagrams, with red for expenses and green for income, but in the net income diagram, expenses do not exist, and income is too high.
As a result the total sum of what is in a wallet is also too high - very annoying.

It's very possible that this is only happening because of something I did wrong, but in this case maybe it should be clearer how to seperate income and expenses correctly, as I've been at it for quite a while now and still can't see my mistake. Maybe add some documentation?

Great app otherwise -thanks

**Comment by AndreAle94** [comment] 2019-01-13 12:59
This happen simply because you have entered the expenses with a negative values. The application is designed to automatically handle the difference between incomes and expenses. You can solve the issue updating all your expenses with a positive value (e.g. an expense of "€ -50.00" should be converted to "€ 50.00"). 
I'm closing the issue because it is not a bug, feel free to reopen it if you need.

**Closed by AndreAle94** 2019-01-13 12:59 UTC

**Comment by test2a** [comment] 2019-02-12 16:54
Uh... shouldnt the software prevent you from making negative entries
