### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by bones-shift** [AndreAle94/moneywallet#160] opened 2020-11-18 10:46 UTC
Why the hell my icons are totally different from these?
![Screenshot_20201118-074536(1)](https://user-images.githubusercontent.com/62573813/99520676-293ff500-2972-11eb-8983-20ed81804ba0.png)
![Screenshot_20201118-074454(1)](https://user-images.githubusercontent.com/62573813/99520678-2a712200-2972-11eb-8c35-632b62792db3.png)

**Comment by AndreAle94** [comment] 2020-11-18 16:52
Duplicate of #129

**Closed by AndreAle94** 2020-11-18 16:52 UTC
