### ISSUE TITLE
Attach any kind of file to a transaction

### ISSUE THREAD

**Issue by Strongsaxophone** [AndreAle94/moneywallet#48] opened 2019-01-21 12:25 UTC
I tried to attach a picture to my transaction but I could not. What kind of attachments is supported ?
It's a good idea to able to attach pictures ( such as your transaction information paper) to your wallet

**Comment by AndreAle94** [comment] 2019-01-22 10:16
Duplicate of #36. It has already been fixed, please wait until the next release.

**Closed by AndreAle94** 2019-01-22 10:16 UTC
